import { useState } from 'react'
import { Link } from 'react-router-dom'
import { Heading } from '@chakra-ui/react'
import { useAuth } from '@/contexts/AuthContext'
import { useStoreQuery } from '@/hooks/useStoreQuery'
import { StoreLoading, StoreNotice, StoreShell } from '@/components/features/store/StoreShell'
import { OrderList } from '@/components/features/store/OrderList'
import { storeAmount, storeCall, storeKey, type StoreConfig, type StoreCursor, type StoreListing } from '../../lib/store'

type SellerData = { profile: { description: string; available: boolean; verified: boolean } | null; account: { legalName: string; phone: string; operator: string; ownsAccount: boolean; identityVerified: boolean; adminApproved: boolean } | null; payable: { available: number; pending: number; payout_pending: number; paid: number; reversed: number } }
function Setup({ initial, reload }: { initial: SellerData; reload: () => void }) {
  const [form, setForm] = useState({ description: initial.profile?.description || '', available: initial.profile?.available ?? true, legalName: initial.account?.legalName || '', phone: initial.account?.phone || '', operator: initial.account?.operator || 'mtn', ownsAccount: initial.account?.ownsAccount || false })
  const [busy, setBusy] = useState(false)
  const [message, setMessage] = useState('')
  return <form className="store-panel store-stack" onSubmit={async (e) => { e.preventDefault(); setBusy(true); try { await storeCall('saveStoreSeller', form); setMessage('Shop settings saved. Changes to payout details require verification again.'); reload() } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'Save failed.') } finally { setBusy(false) } }}>
    <Heading as="h2" size="lg">Your shop</Heading><label>About your shop<textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><label><input type="checkbox" checked={form.available} onChange={(e) => setForm({ ...form, available: e.target.checked })} />Available for new orders</label>
    <Heading as="h2" size="lg">ZMW payout setup</Heading><p className="store-muted">Optional for Points sales. Club BZR verifies your identity and payout account before approving ZMW seller payouts. These details are private.</p><div className="store-grid"><label>Legal name<input value={form.legalName} onChange={(e) => setForm({ ...form, legalName: e.target.value })} /></label><label>Zambian mobile-money number<input type="tel" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /></label><label>Operator<select value={form.operator} onChange={(e) => setForm({ ...form, operator: e.target.value })}><option value="mtn">MTN</option><option value="airtel">Airtel</option><option value="zamtel">Zamtel</option></select></label></div><label><input type="checkbox" checked={form.ownsAccount} onChange={(e) => setForm({ ...form, ownsAccount: e.target.checked })} />I confirm this mobile-money account belongs to me.</label><p className="store-muted">Verification: {initial.account?.adminApproved ? 'Approved' : 'Awaiting review'}</p>{message && <StoreNotice>{message}</StoreNotice>}<button type="submit" className="store-button primary" disabled={busy}>{busy ? 'Saving…' : 'Save shop settings'}</button>
  </form>
}
function Listings({ storeEnabled }: { storeEnabled: boolean }) {
  const [cursor, setCursor] = useState<StoreCursor>(null)
  const query = useStoreQuery<{ items: StoreListing[]; cursor: StoreCursor }>('getStoreWorkspace', { mode: 'listings', cursor })
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  async function act(id: string, action: string) { setBusy(true); setError(''); try { await storeCall('moderateStoreListing', { listingId: id, action }); query.reload() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Action failed.') } finally { setBusy(false) } }
  return <div className="store-stack">{storeEnabled && <div><Link className="store-button primary" to="/store/manage/new">Create a release</Link></div>}{query.loading && <StoreLoading />}{(error || query.error) && <StoreNotice error>{error || query.error}</StoreNotice>}{storeEnabled && query.data?.items.length === 0 && <StoreNotice>Your shop starts with one release. Create a draft and submit it for review.</StoreNotice>}{query.data?.items.map((l) => <div className="store-panel store-stack" key={l.id}><div className="store-actions" style={{ justifyContent: 'space-between' }}><Heading as="h2" size="md">{l.title}</Heading><span className="store-tag">{l.status.replaceAll('_', ' ')} · v{l.version}</span></div><div className="store-actions"><Link className="store-button" to={`/store/${l.id}`}>Preview</Link>{storeEnabled && ['draft', 'paused', 'sold_out'].includes(l.status) && <><Link className="store-button" to={`/store/manage/${l.id}/edit`}>Edit</Link><button disabled={busy} className="store-button" onClick={() => act(l.id, 'submit')}>Send for review</button></>}{l.status === 'published' && <button disabled={busy} className="store-button" onClick={() => act(l.id, 'pause')}>Pause</button>}{l.status !== 'archived' && <button disabled={busy} className="store-button" onClick={() => act(l.id, 'archive')}>Archive</button>}</div></div>)}<div className="store-actions">{cursor && <button className="store-button" onClick={() => setCursor(null)}>First page</button>}{query.data?.cursor && <button className="store-button" onClick={() => setCursor(query.data!.cursor)}>Next listings</button>}</div></div>
}
function Payouts({ seller, enabled }: { seller: SellerData; enabled: boolean }) {
  const [amount, setAmount] = useState('')
  const [key, setKey] = useState(storeKey)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const query = useStoreQuery<{ items: Array<{ id: string; amountNgwee: number; status: string; payoutFeeNgwee?: number; createdAt: number }>; cursor: StoreCursor }>('getStoreWorkspace', { mode: 'payouts' })
  return <div className="store-stack">{!enabled && <StoreNotice>ZMW seller payouts are currently unavailable. Your earnings and payout history remain accessible.</StoreNotice>}<form className="store-panel store-stack" onSubmit={async (e) => { e.preventDefault(); setBusy(true); setError(''); try { await storeCall('requestStorePayout', { currency: 'ZMW', amountNgwee: Number(amount), idempotencyKey: key }); setKey(storeKey()); query.reload() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Payout request failed.') } finally { setBusy(false) } }}><Heading as="h2" size="lg">Request a ZMW payout</Heading><p>Available seller earnings: {storeAmount(seller.payable.available, 'ZMW')}</p><label>Amount in ngwee (100 ngwee = ZMW 1)<input type="number" min="1" step="1" required value={amount} onChange={(e) => { setAmount(e.target.value); setKey(storeKey()) }} /></label><p className="store-muted">Only approved, verified sellers can request payouts while Club BZR enables them. Points are never withdrawable. Club BZR covers provider payout costs in this release.</p><button disabled={busy || !enabled || !seller.account?.adminApproved} className="store-button primary" type="submit">{busy ? 'Requesting…' : 'Request payout'}</button></form>{error && <StoreNotice error>{error}</StoreNotice>}{query.loading && <StoreLoading />}{query.error && <StoreNotice error>{query.error}</StoreNotice>}{query.data?.items.map((p) => <div key={p.id} className="store-panel store-stack"><strong>{storeAmount(p.amountNgwee, 'ZMW')} · {p.status.replaceAll('_', ' ')}</strong><p className="store-muted">{new Date(p.createdAt).toLocaleDateString()}</p>{!['paid', 'failed'].includes(p.status) && <button className="store-button" disabled={busy} onClick={async () => { setBusy(true); try { await storeCall('checkStorePayout', { payoutId: p.id }); query.reload() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Payout reconciliation failed.') } finally { setBusy(false) } }}>Check payout</button>}</div>)}</div>
}
function Manager() {
  const [tab, setTab] = useState('listings')
  const { hasRole } = useAuth()
  const config = useStoreQuery<StoreConfig>('getStoreConfig')
  const seller = useStoreQuery<SellerData>('getStoreSeller')
  const summary = useStoreQuery<{ pointsEarned: number }>('getStoreSellerSummary')
  if (seller.loading || config.loading) return <StoreLoading />
  if (seller.error) return <StoreNotice error>{seller.error}</StoreNotice>
  if (!seller.data) return null
  const storeEnabled = config.data?.storeEnabled === true
  const needsSetup = tab === 'settings' || (tab === 'listings' && !seller.data.profile)
  return <>
    {config.error ? <StoreNotice error>Store availability could not be checked. {config.error}<div className="store-actions"><button className="store-button" onClick={config.reload}>Check Store status</button></div></StoreNotice> : !storeEnabled && <StoreNotice><strong>The Store is currently closed.</strong><p>Shop setup and new releases are unavailable. Existing orders and earnings remain accessible.</p>{hasRole(['admin']) ? <p>Enable Store open in Store controls to allow shop setup.</p> : <p>Shop setup will be available when Club BZR opens the Store.</p>}<div className="store-actions" style={{ marginTop: 16 }}>{hasRole(['admin']) && <Link className="store-button primary" to="/admin/store?tab=controls">Open Store controls</Link>}<button className="store-button" onClick={config.reload}>Check Store status</button></div></StoreNotice>}
    <div className="store-actions" style={{ marginBottom: 28 }}>{['listings', 'orders', 'earnings', 'payouts', 'settings'].map((t) => <button key={t} className={`store-button ${tab === t ? 'primary' : ''}`} onClick={() => setTab(t)}>{t.charAt(0).toUpperCase() + t.slice(1)}</button>)}</div>{needsSetup ? (storeEnabled ? <Setup initial={seller.data} reload={seller.reload} /> : null) : tab === 'listings' ? <Listings storeEnabled={storeEnabled} /> : tab === 'orders' ? <OrderList mode="sales" /> : tab === 'payouts' ? <Payouts seller={seller.data} enabled={storeEnabled && config.data?.sellerPayoutsEnabled === true && config.data?.zmwCheckoutEnabled === true} /> : <div className="store-stack"><div className="store-grid">{[['Pending ZMW earnings', seller.data.payable.pending], ['Available ZMW earnings', seller.data.payable.available], ['Payout pending', seller.data.payable.payout_pending], ['Paid out', seller.data.payable.paid]].map(([label, value]) => <div className="store-panel store-stack" key={label}><span>{label}</span><Heading size="xl">{storeAmount(Number(value), 'ZMW')}</Heading></div>)}</div><div className="store-panel store-stack"><Heading as="h2" size="lg">Points from completed sales</Heading><strong>{summary.data ? storeAmount(summary.data.pointsEarned, 'POINT') : 'Loading…'}</strong><p className="store-muted">These are closed-loop Club BZR Points. They create no ZMW seller earnings and cannot be paid out.</p><Link to="/wallet">Open Points wallet →</Link></div></div>}</>
}
export default function StoreManage() {
  const { firebaseUser, initialized } = useAuth()
  return <StoreShell title="Your art. Your shop." description="Publish releases, manage commissions and originals, and keep track of every sale.">{!initialized ? <StoreLoading /> : !firebaseUser ? <StoreNotice><Link to="/auth/login">Sign in to manage your shop.</Link></StoreNotice> : <Manager />}</StoreShell>
}
