import { useState, type FormEvent } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { Heading, Image } from '@chakra-ui/react'
import { useAuth } from '@/contexts/AuthContext'
import { useStoreQuery } from '@/hooks/useStoreQuery'
import { StoreLoading, StoreNotice, StoreShell } from '@/components/features/store/StoreShell'
import { StoreFiles } from '@/components/features/store/StoreFiles'
import { parseStorePrice, storeAmount, storeCall, storeKey, storeLabels, uploadStoreCover, type ProductType, type StoreAsset, type StoreConfig, type StoreListing } from '../../lib/store'

const defaultFulfilment: StoreListing['fulfilment'] = { estimatedDays: 7, revisionRounds: 1, questions: [], addOns: [], dimensions: '', weightGrams: null, materials: '', framed: false, condition: '', oneOfOne: false, deliveryOptions: [], pickup: false }
function EditorForm({ listing, assets, config, uid, collectionPosts }: { listing?: StoreListing; assets: StoreAsset[]; config: StoreConfig; uid: string; collectionPosts: Array<{ id: string; title: string; body: string }> }) {
  const navigate = useNavigate()
  const [kind, setKind] = useState<ProductType>(listing?.productType || 'digital_release')
  const [title, setTitle] = useState(listing?.title || '')
  const [description, setDescription] = useState(listing?.description || '')
  const [cover, setCover] = useState(listing?.coverImage || '')
  const [images, setImages] = useState<string[]>(listing?.images || [])
  const [tags, setTags] = useState(listing?.tags.join(', ') || '')
  const [price, setPrice] = useState(listing ? `${Math.floor(listing.priceNgwee / 100)}.${String(listing.priceNgwee % 100).padStart(2, '0')}` : '')
  const [points, setPoints] = useState(String(listing?.pricePoints || ''))
  const [usePoints, setUsePoints] = useState(listing?.acceptedPaymentMethods.includes('POINT') ?? true)
  const [useZmw, setUseZmw] = useState(listing?.acceptedPaymentMethods.includes('ZMW') ?? false)
  const [inventory, setInventory] = useState(listing?.inventory?.toString() || '')
  const [licence, setLicence] = useState(listing?.licence.kind || '')
  const [files, setFiles] = useState(assets)
  const [posts, setPosts] = useState(collectionPosts)
  const [limit, setLimit] = useState(listing?.downloadLimit?.toString() || '')
  const [fulfilment, setFulfilment] = useState(listing?.fulfilment || defaultFulfilment)
  const [promote, setPromote] = useState(listing?.promoteOnPublish ?? true)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const [savedId] = useState(listing?.id || storeKey())
  function updateQuestion(index: number, values: Partial<StoreListing['fulfilment']['questions'][number]>) { setFulfilment({ ...fulfilment, questions: fulfilment.questions.map((q, i) => i === index ? { ...q, ...values } : q) }) }
  async function submit(event: FormEvent) {
    event.preventDefault(); setBusy(true); setError('')
    try {
      const result = await storeCall<{ listingId: string }>('saveStoreListing', { id: savedId, version: listing?.version, productType: kind, title, description, coverImage: cover, images, tags: tags.split(',').map((s) => s.trim()).filter(Boolean), priceNgwee: parseStorePrice(price), pricePoints: usePoints ? Number(points) : null, acceptedPaymentMethods: [...(usePoints ? ['POINT'] : []), ...(useZmw ? ['ZMW'] : [])], inventory: inventory === '' ? null : Number(inventory), licenceKind: licence, assets: files, collectionPosts: posts, downloadLimit: limit === '' ? null : Number(limit), fulfilment, promoteOnPublish: promote })
      navigate(`/store/manage?listing=${result.listingId}`)
    } catch (cause) { setError(cause instanceof Error ? cause.message : 'Listing could not be saved.') }
    finally { setBusy(false) }
  }
  const estimatedFee = points && Number.isSafeInteger(Number(points)) ? Number(BigInt(Number(points)) * BigInt(config.feeBasisPoints) / BigInt(10000)) : 0
  return <form className="store-stack" onSubmit={submit} style={{ maxWidth: 960 }}>
    <div className="store-panel store-stack"><Heading as="h2" size="lg">The release</Heading><div className="store-grid"><label>Product type<select value={kind} onChange={(e) => setKind(e.target.value as ProductType)}>{Object.entries(storeLabels).map(([value, label]) => <option key={value} value={value} disabled={(value === 'physical_original' && !config.physicalProductsEnabled) || (value === 'gated_collection' && !config.gatedCollectionsEnabled)}>{label}</option>)}</select></label><label>Title<input required minLength={3} maxLength={120} value={title} onChange={(e) => setTitle(e.target.value)} /></label></div><label>Description<textarea required minLength={20} maxLength={12000} value={description} onChange={(e) => setDescription(e.target.value)} placeholder="What are you releasing? Tell buyers what's included and how they can use it." /></label><label>Tags, separated by commas<input value={tags} onChange={(e) => setTags(e.target.value)} placeholder="portrait, brushes, illustration" /></label>
      <label>Cover image<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={async (e) => { const file = e.target.files?.[0]; if (!file) return; setBusy(true); try { setCover(await uploadStoreCover(file, uid)) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Upload failed.') } finally { setBusy(false) } }} /></label>{cover && <Image src={cover} alt="Release cover preview" maxH="280px" rounded="lg" objectFit="contain" />}
      <label>Additional preview images<input type="file" multiple accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={async (e) => { const selected = Array.from(e.target.files || []); setBusy(true); try { setImages([...images, ...await Promise.all(selected.map((file) => uploadStoreCover(file, uid)))].slice(0, 8)) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Upload failed.') } finally { setBusy(false) } }} /></label><div className="store-actions">{images.map((url) => <button key={url} type="button" aria-label="Remove preview image" onClick={() => setImages(images.filter((item) => item !== url))}><Image src={url} alt="Additional preview" boxSize="70px" objectFit="cover" /></button>)}</div>
    </div>
    <div className="store-panel store-stack"><Heading as="h2" size="lg">Pricing and licence</Heading><div className="store-actions"><label><input type="checkbox" checked={usePoints} onChange={(e) => setUsePoints(e.target.checked)} />Accept Points</label><label><input type="checkbox" checked={useZmw} onChange={(e) => setUseZmw(e.target.checked)} />Accept ZMW</label></div><div className="store-grid"><label>Artist’s ZMW price<input type="text" inputMode="decimal" required value={price} onChange={(e) => setPrice(e.target.value)} placeholder="50.00" /></label>{usePoints && <label>Independent Points price<input type="number" required min={config.minimumPricePoints} step="1" value={points} onChange={(e) => setPoints(e.target.value)} /></label>}<label>{kind === 'physical_original' ? 'Inventory quantity' : 'Available quantity (leave blank for unlimited)'}<input type="number" required={kind === 'physical_original'} min="0" step="1" value={inventory} onChange={(e) => setInventory(e.target.value)} /></label><label>Licence<select required value={licence} onChange={(e) => setLicence(e.target.value)}><option value="">Choose a licence</option><option value="personal">Personal</option><option value="commercial">Commercial</option></select></label></div>
      <p className="store-muted">Club BZR’s current platform fee is {config.feeBasisPoints / 100}% of the product subtotal, rounded down. Delivery is excluded. Each purchase keeps the fee in effect at funding.{usePoints && points && ` You receive ${storeAmount(Number(points) - estimatedFee, 'POINT')} before any add-ons.`}</p>{useZmw && !config.zmwCheckoutEnabled && <StoreNotice>ZMW prices can be prepared now. Buyers can use ZMW after Club BZR enables marketplace collection.</StoreNotice>}
    </div>
    {['digital_release', 'gated_collection'].includes(kind) && <div className="store-panel store-stack"><Heading as="h2" size="lg">{kind === 'gated_collection' ? 'Collection resources' : 'Digital delivery'}</Heading><StoreFiles files={files} onChange={setFiles} />{kind === 'gated_collection' && <fieldset className="store-stack"><legend>Protected collection posts</legend>{posts.map((post, i) => <div className="store-stack" key={post.id}><label>Post title<input required value={post.title} onChange={(e) => setPosts(posts.map((p, index) => i === index ? { ...p, title: e.target.value } : p))} /></label><label>Members-only post<textarea required value={post.body} onChange={(e) => setPosts(posts.map((p, index) => i === index ? { ...p, body: e.target.value } : p))} /></label><button type="button" className="store-button" onClick={() => setPosts(posts.filter((_, index) => i !== index))}>Remove post</button></div>)}<button type="button" className="store-button" onClick={() => setPosts([...posts, { id: storeKey(), title: '', body: '' }])}>Add protected post</button></fieldset>}<label>Download request limit (optional)<input type="number" min="1" step="1" value={limit} onChange={(e) => setLimit(e.target.value)} /></label><p className="store-muted">Files stay private until a completed purchase. For collections, publish a new version to make updates available to existing buyers.</p></div>}
    {['bespoke_request', 'physical_original'].includes(kind) && <div className="store-panel store-stack"><Heading as="h2" size="lg">Fulfilment</Heading><div className="store-grid"><label>Estimated preparation / delivery days<input type="number" min="1" max="365" value={fulfilment.estimatedDays} onChange={(e) => setFulfilment({ ...fulfilment, estimatedDays: Number(e.target.value) })} /></label>{kind === 'bespoke_request' && <label>Included revision rounds<input type="number" min="0" max="20" value={fulfilment.revisionRounds} onChange={(e) => setFulfilment({ ...fulfilment, revisionRounds: Number(e.target.value) })} /></label>}</div>
      {kind === 'physical_original' && <><div className="store-grid"><label>Dimensions<input required value={fulfilment.dimensions} onChange={(e) => setFulfilment({ ...fulfilment, dimensions: e.target.value })} placeholder="40 × 60 cm" /></label><label>Materials and medium<input required value={fulfilment.materials} onChange={(e) => setFulfilment({ ...fulfilment, materials: e.target.value })} /></label><label>Condition<input required value={fulfilment.condition} onChange={(e) => setFulfilment({ ...fulfilment, condition: e.target.value })} /></label><label>Weight in grams (optional)<input type="number" value={fulfilment.weightGrams ?? ''} onChange={(e) => setFulfilment({ ...fulfilment, weightGrams: e.target.value ? Number(e.target.value) : null })} /></label></div><div className="store-actions"><label><input type="checkbox" checked={fulfilment.oneOfOne} onChange={(e) => { setFulfilment({ ...fulfilment, oneOfOne: e.target.checked }); if (e.target.checked) setInventory('1') }} />One of one</label><label><input type="checkbox" checked={fulfilment.framed} onChange={(e) => setFulfilment({ ...fulfilment, framed: e.target.checked })} />Framed</label><label><input type="checkbox" checked={fulfilment.pickup} onChange={(e) => setFulfilment({ ...fulfilment, pickup: e.target.checked })} />Lusaka pickup</label></div>
        <fieldset className="store-stack"><legend>Delivery regions and charges</legend>{config.deliveryRegions.map((region) => { const option = fulfilment.deliveryOptions.find((d) => d.region === region); return <div key={region} className="store-grid"><label><input type="checkbox" checked={!!option} onChange={(e) => setFulfilment({ ...fulfilment, deliveryOptions: e.target.checked ? [...fulfilment.deliveryOptions, { region, priceNgwee: 0, pricePoints: 0 }] : fulfilment.deliveryOptions.filter((d) => d.region !== region) })} />{region}</label>{option && <><label>Delivery charge (ngwee)<input type="number" min="0" step="1" value={option.priceNgwee} onChange={(e) => setFulfilment({ ...fulfilment, deliveryOptions: fulfilment.deliveryOptions.map((d) => d.region === region ? { ...d, priceNgwee: Number(e.target.value) } : d) })} /></label><label>Delivery charge (Points)<input type="number" min="0" step="1" value={option.pricePoints} onChange={(e) => setFulfilment({ ...fulfilment, deliveryOptions: fulfilment.deliveryOptions.map((d) => d.region === region ? { ...d, pricePoints: Number(e.target.value) } : d) })} /></label></>}</div> })}</fieldset></>}
      <fieldset className="store-stack"><legend>{kind === 'bespoke_request' ? 'Brief questions' : 'Personalization questions'}</legend>{fulfilment.questions.map((q, i) => <div key={q.id} className="store-stack" style={{ borderBottom: '1px solid #333', paddingBottom: 20 }}><div className="store-grid"><label>Question<input required value={q.label} onChange={(e) => updateQuestion(i, { label: e.target.value })} /></label><label>Answer type<select value={q.type} onChange={(e) => updateQuestion(i, { type: e.target.value as typeof q.type })}><option value="short_text">Short text</option><option value="long_text">Long text</option><option value="single_choice">Choose one</option><option value="multiple_choice">Choose multiple</option><option value="reference_image">Reference image</option></select></label></div>{q.type.includes('choice') && <label>Choices, separated by commas<input value={q.options.join(', ')} onChange={(e) => updateQuestion(i, { options: e.target.value.split(',').map((v) => v.trim()) })} /></label>}<div className="store-actions"><label><input type="checkbox" checked={q.required} onChange={(e) => updateQuestion(i, { required: e.target.checked })} />Required</label><button type="button" className="store-button" onClick={() => setFulfilment({ ...fulfilment, questions: fulfilment.questions.filter((_, index) => index !== i) })}>Remove question</button></div></div>)}<button type="button" className="store-button" onClick={() => setFulfilment({ ...fulfilment, questions: [...fulfilment.questions, { id: storeKey(), label: '', type: 'long_text', required: true, options: [] }] })}>Add question</button></fieldset>
      {kind === 'bespoke_request' && <fieldset className="store-stack"><legend>Optional add-ons</legend>{fulfilment.addOns.map((a, i) => <div className="store-grid" key={a.id}><label>Add-on title<input required value={a.title} onChange={(e) => setFulfilment({ ...fulfilment, addOns: fulfilment.addOns.map((item, index) => i === index ? { ...item, title: e.target.value } : item) })} /></label>{(['priceNgwee', 'pricePoints'] as const).map((field) => <label key={field}>{field === 'priceNgwee' ? 'Additional price (ngwee)' : 'Additional Points'}<input type="number" min="0" value={a[field]} onChange={(e) => setFulfilment({ ...fulfilment, addOns: updateAddOnPrice(fulfilment.addOns, i, field, Number(e.target.value)) })} /></label>)}<button type="button" className="store-button" onClick={() => setFulfilment({ ...fulfilment, addOns: fulfilment.addOns.filter((_, index) => index !== i) })}>Remove add-on</button></div>)}<button type="button" className="store-button" onClick={() => setFulfilment({ ...fulfilment, addOns: [...fulfilment.addOns, { id: storeKey(), title: '', priceNgwee: 0, pricePoints: 0 }] })}>Add optional extra</button></fieldset>}
    </div>}
    <label className="store-inline"><input type="checkbox" checked={promote} onChange={(e) => setPromote(e.target.checked)} />Share a Community Wall post when this version is approved.</label>
    {error && <StoreNotice error>{error}</StoreNotice>}<div className="store-actions"><button className="store-button primary" type="submit" disabled={busy || !cover}>{busy ? 'Saving…' : 'Save draft'}</button><Link className="store-button" to="/store/manage">Back to shop</Link></div>
  </form>
}
function updateAddOnPrice(items: StoreListing['fulfilment']['addOns'], index: number, field: 'priceNgwee' | 'pricePoints', value: number) { return items.map((item, i) => i === index ? { ...item, [field]: value } : item) }
export default function StoreEditor() {
  const { listingId } = useParams()
  const { firebaseUser, initialized } = useAuth()
  const config = useStoreQuery<StoreConfig>('getStoreConfig')
  const listing = useStoreQuery<{ listing: StoreListing; assets: StoreAsset[]; collectionPosts: Array<{ id: string; title: string; body: string }> }>('getStoreListing', { listingId }, !!listingId && !!firebaseUser)
  return <StoreShell title={listingId ? 'Edit your release.' : 'Create a release.'} description="Make something worth keeping. Prepare a draft, then send it to Club BZR for review.">{(!initialized || config.loading || listing.loading) && <StoreLoading />}{(config.error || listing.error) && <StoreNotice error>{config.error || listing.error}</StoreNotice>}{initialized && !firebaseUser ? <StoreNotice><Link to="/auth/login">Sign in to manage your shop.</Link></StoreNotice> : config.data && firebaseUser && (!listingId || listing.data) ? <EditorForm key={listingId || 'new'} uid={firebaseUser.uid} config={config.data} listing={listing.data?.listing} assets={listing.data?.assets || []} collectionPosts={listing.data?.collectionPosts || []} /> : null}</StoreShell>
}
