'use client'

import { useEffect, useMemo, useRef, useState, type CSSProperties, type FormEvent, type ReactNode } from 'react'
import { Badge, Box, Button, Checkbox, Flex, Grid, Heading, HStack, Image, Input, SimpleGrid, Table, Text, VStack } from '@chakra-ui/react'
import { AnimatePresence, motion } from 'framer-motion'
import { httpsCallable } from 'firebase/functions'
import { Activity, AlertTriangle, Ban, Check, ChevronLeft, ChevronRight, CircleOff, Clock3, Copy, Download, ExternalLink, KeyRound, MoreHorizontal, Search, Send, UserPlus, UsersRound, X } from 'lucide-react'
import { AdminLayout } from '@/components/layout/AdminLayout'
import { useRealtimeCollection } from '@/hooks'
import { PERMISSION_LABELS, ROLE_DEFINITIONS, roleLabel } from '@/lib/rbac'
import { functions } from '../../../lib/config'
import type { AuditLog, CreativePassport, QuestSubmission, SessionRegistration, User as FirestoreUser, UserAccountStatus, UserRole } from '../../../lib/schema'

const MotionBox = motion.create(Box)
const saveUserFn = httpsCallable(functions, 'adminSaveUser')
const getAuthDetailsFn = httpsCallable(functions, 'adminGetUserAuthDetails')
const createInviteFn = httpsCallable(functions, 'adminCreateInviteProfile')
type UserState = 'active' | 'onboarding' | 'invited' | 'suspended' | 'closed'
type DrawerTab = 'overview' | 'access' | 'activity' | 'account' | 'audit'
interface ManagedUser { id: string; displayName: string; email: string; username: string; avatar?: string; role: UserRole; accountStatus: UserAccountStatus; state: UserState; createdAt: unknown; lastActiveAt: unknown; sessions: number; quests: number; submissions: number }
interface EditForm { displayName: string; email: string; username: string; role: UserRole; accountStatus: UserAccountStatus }
interface AuthDetails { emailVerified: boolean; disabled: boolean; createdAt: string | null; lastSignInAt: string | null }
interface InviteForm { displayName: string; email: string; username: string; role: UserRole }
const PAGE_SIZE = 10
const roles = Object.keys(ROLE_DEFINITIONS) as UserRole[]
const stateLabels: Record<UserState, string> = { active: 'Active', onboarding: 'Onboarding incomplete', invited: 'Invited', suspended: 'Suspended', closed: 'Closed' }
const selectStyle: CSSProperties = { width: '100%', minHeight: 44, padding: '0 38px 0 13px', color: '#f7f5f2', background: '#0d0d0d', border: '1px solid rgba(255,255,255,.15)', borderRadius: 9, outline: 'none' }

function toDate(value: unknown): Date | null { if (!value) return null; if (value instanceof Date) return value; if (typeof value === 'string') { const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? null : parsed } if (typeof value === 'object' && value && 'toDate' in value && typeof value.toDate === 'function') return value.toDate(); return null }
const toMillis = (value: unknown) => toDate(value)?.getTime() || 0
function formatDate(value: unknown, time = false) { const date = toDate(value); if (!date) return 'Never'; return new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric', ...(time ? { hour: 'numeric', minute: '2-digit' } : {}) }).format(date) }
function relativeDate(value: unknown) { const date = toDate(value); if (!date) return 'Never'; const diff = Date.now() - date.getTime(); if (diff < 60_000) return 'Just now'; if (diff < 3_600_000) return `${Math.floor(diff / 60_000)}m ago`; if (diff < 86_400_000) return `${Math.floor(diff / 3_600_000)}h ago`; if (diff < 604_800_000) return `${Math.floor(diff / 86_400_000)}d ago`; return formatDate(date) }
function getAccountStatus(user: FirestoreUser): UserAccountStatus { if (user.accountStatus === 'closed') return 'closed'; if (user.accountStatus === 'suspended' || user.isActive === false) return 'suspended'; return 'active' }
function getState(user: FirestoreUser): UserState { const status = getAccountStatus(user); if (status !== 'active') return status; if (user.invitationStatus === 'pending') return 'invited'; if (!user.isOnboarded) return 'onboarding'; return 'active' }
function buildUsers(userDocs: FirestoreUser[], passports: CreativePassport[], submissions: QuestSubmission[], registrations: SessionRegistration[]): ManagedUser[] {
  const passportMap = new Map(passports.map((item) => [item.userId, item])); const submissionMap = new Map<string, QuestSubmission[]>(); const registrationMap = new Map<string, Set<string>>()
  submissions.forEach((item) => submissionMap.set(item.userId, [...(submissionMap.get(item.userId) || []), item]))
  registrations.filter((item) => item.status === 'confirmed').forEach((item) => { const sessionIds = registrationMap.get(item.userId) || new Set<string>(); sessionIds.add(item.sessionId); registrationMap.set(item.userId, sessionIds) })
  return userDocs.map((user) => { const uid = user.uid || user.id; const passport = passportMap.get(uid); const ownSubmissions = submissionMap.get(uid) || []; const approved = new Set(ownSubmissions.filter((item) => item.approved).map((item) => item.questId)); return { id: uid, displayName: user.displayName || 'Unnamed member', email: user.email || '', username: (user as FirestoreUser & { username?: string }).username || user.email?.split('@')[0] || uid.slice(0, 8), avatar: user.photoURL || undefined, role: user.role || 'user', accountStatus: getAccountStatus(user), state: getState(user), createdAt: user.createdAt, lastActiveAt: user.lastActiveAt, sessions: registrationMap.get(uid)?.size || passport?.eventsAttended?.length || 0, quests: Math.max(approved.size, passport?.questsCompleted?.length || 0), submissions: ownSubmissions.length } }).sort((a, b) => toMillis(b.createdAt) - toMillis(a.createdAt))
}
const initialInvite: InviteForm = { displayName: '', email: '', username: '', role: 'user' }

export default function ManageUsers() {
  const usersQuery = useRealtimeCollection('users', { orderBy: 'createdAt', orderDirection: 'desc' }); const passportsQuery = useRealtimeCollection('creativePassports'); const submissionsQuery = useRealtimeCollection('questSubmissions'); const registrationsQuery = useRealtimeCollection('sessionRegistrations'); const auditQuery = useRealtimeCollection('auditLogs', { orderBy: 'createdAt', orderDirection: 'desc', limit: 200 })
  const [search, setSearch] = useState(''); const [roleFilter, setRoleFilter] = useState<UserRole | 'all'>('all'); const [stateFilter, setStateFilter] = useState<UserState | 'all'>('all'); const [page, setPage] = useState(1); const [selectedId, setSelectedId] = useState<string | null>(null); const [tab, setTab] = useState<DrawerTab>('overview'); const [form, setForm] = useState<EditForm | null>(null); const [authDetails, setAuthDetails] = useState<AuthDetails | null>(null); const [authLoading, setAuthLoading] = useState(false); const [saving, setSaving] = useState(false); const [menuId, setMenuId] = useState<string | null>(null); const [inviteOpen, setInviteOpen] = useState(false); const [invite, setInvite] = useState(initialInvite); const [inviteSaving, setInviteSaving] = useState(false); const [feedback, setFeedback] = useState<{ tone: 'success' | 'error' | 'warning'; message: string } | null>(null); const openerRef = useRef<HTMLElement | null>(null)
  const users = useMemo(() => buildUsers(usersQuery.data, passportsQuery.data, submissionsQuery.data, registrationsQuery.data), [usersQuery.data, passportsQuery.data, submissionsQuery.data, registrationsQuery.data]); const selectedUser = users.find((user) => user.id === selectedId) || null
  const filtered = useMemo(() => { const query = search.trim().toLowerCase(); return users.filter((user) => (!query || `${user.displayName} ${user.email} ${user.username}`.toLowerCase().includes(query)) && (roleFilter === 'all' || user.role === roleFilter) && (stateFilter === 'all' || user.state === stateFilter)) }, [users, search, roleFilter, stateFilter])
  const totalPages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const currentPage = Math.min(page, totalPages); const pageUsers = filtered.slice((currentPage - 1) * PAGE_SIZE, currentPage * PAGE_SIZE); const selectedAudit = useMemo(() => auditQuery.data.filter((item) => item.targetId === selectedId), [auditQuery.data, selectedId])
  useEffect(() => { if (!feedback) return; const timer = window.setTimeout(() => setFeedback(null), 4200); return () => window.clearTimeout(timer) }, [feedback])
  useEffect(() => { if (!selectedId && !inviteOpen) return; const close = (event: KeyboardEvent) => { if (event.key === 'Escape') { setSelectedId(null); setInviteOpen(false) } }; document.body.style.overflow = 'hidden'; window.addEventListener('keydown', close); return () => { document.body.style.overflow = ''; window.removeEventListener('keydown', close) } }, [selectedId, inviteOpen])
  const openUser = (user: ManagedUser, target?: HTMLElement) => { openerRef.current = target || document.activeElement as HTMLElement; setForm({ displayName: user.displayName, email: user.email, username: user.username, role: user.role, accountStatus: user.accountStatus }); setAuthLoading(true); setAuthDetails(null); setSelectedId(user.id); setTab('overview'); setMenuId(null); void getAuthDetailsFn({ userId: user.id }).then((result) => setAuthDetails(result.data as AuthDetails)).catch(() => setAuthDetails(null)).finally(() => setAuthLoading(false)) }
  const closeDrawer = () => { setSelectedId(null); window.setTimeout(() => openerRef.current?.focus(), 0) }
  const save = async (next?: Partial<EditForm>) => { if (!selectedUser || !form) return; const payload = { ...form, ...next }; if (!payload.displayName.trim() || !payload.email.trim() || !payload.username.trim()) { setFeedback({ tone: 'error', message: 'Name, email, and username are required.' }); return } setSaving(true); try { await saveUserFn({ userId: selectedUser.id, displayName: payload.displayName.trim(), email: payload.email.trim(), username: payload.username.trim().replace(/^@/, ''), role: payload.role, accountStatus: payload.accountStatus }); setForm(payload); setFeedback({ tone: payload.accountStatus === 'active' ? 'success' : 'warning', message: 'User changes saved and access synchronized.' }) } catch (error) { setFeedback({ tone: 'error', message: error instanceof Error ? error.message : 'Could not save this user.' }) } finally { setSaving(false) } }
  const createInvite = async (event: FormEvent) => { event.preventDefault(); if (!invite.displayName.trim() || !invite.email.trim()) { setFeedback({ tone: 'error', message: 'Name and email are required.' }); return } setInviteSaving(true); try { const result = await createInviteFn({ ...invite, username: invite.username.trim().replace(/^@/, '') || invite.email.split('@')[0] }); const setupLink = (result.data as { setupLink?: string }).setupLink; if (setupLink) await navigator.clipboard.writeText(setupLink); setFeedback({ tone: 'success', message: setupLink ? 'Invitation created. The secure setup link was copied.' : 'Invitation created.' }); setInvite(initialInvite); setInviteOpen(false) } catch (error) { setFeedback({ tone: 'error', message: error instanceof Error ? error.message : 'Could not create this invitation.' }) } finally { setInviteSaving(false) } }
  const exportCsv = () => { const header = ['Name', 'Email', 'Username', 'Role', 'State', 'Last activity', 'Sessions', 'Quests', 'Submissions', 'Joined']; const lines = filtered.map((user) => [user.displayName, user.email, user.username, roleLabel(user.role), stateLabels[user.state], formatDate(user.lastActiveAt, true), user.sessions, user.quests, user.submissions, formatDate(user.createdAt)].map((value) => `"${String(value).replace(/"/g, '""')}"`).join(',')); const url = URL.createObjectURL(new Blob([[header.join(','), ...lines].join('\n')], { type: 'text/csv' })); const link = document.createElement('a'); link.href = url; link.download = `club-bzr-users-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(url) }
  const loading = usersQuery.loading || passportsQuery.loading || submissionsQuery.loading || registrationsQuery.loading; const counts = { active: users.filter((user) => user.state === 'active').length, onboarding: users.filter((user) => user.state === 'onboarding').length, invited: users.filter((user) => user.state === 'invited').length, restricted: users.filter((user) => ['suspended', 'closed'].includes(user.state)).length }
  return <AdminLayout><Box px={{ base: 4, md: 7, xl: 9 }} py={{ base: 6, md: 8 }} maxW="1600px">
    <Flex align={{ base: 'stretch', md: 'center' }} justify="space-between" direction={{ base: 'column', md: 'row' }} gap={4} mb={6}><HStack align="baseline" gap={4}><Heading as="h1" color="white" fontSize={{ base: '2xl', md: '3xl' }}>Users</Heading><Text color="rgba(255,255,255,.48)" fontSize="sm">{filtered.length} results</Text></HStack><HStack gap={3}><Button onClick={exportCsv} variant="outline" borderColor="whiteAlpha.200" color="white" bg="transparent" borderRadius="lg"><Download size={16} /> Export</Button><Button onClick={() => setInviteOpen(true)} bg="brand.500" color="white" borderRadius="lg" _hover={{ bg: 'brand.600' }}><UserPlus size={16} /> Invite user</Button></HStack></Flex>
    <Box border="1px solid rgba(255,255,255,.09)" borderRadius="xl" bg="#101010" mb={4}><SimpleGrid columns={{ base: 2, md: 5 }}><SummaryMetric icon={<UsersRound size={17} />} value={users.length} label="Total users" color="#d9d9d9" /><SummaryMetric icon={<Check size={17} />} value={counts.active} label="Active" color="#65c466" /><SummaryMetric icon={<Clock3 size={17} />} value={counts.onboarding} label="Onboarding" color="#e4b93f" /><SummaryMetric icon={<Send size={17} />} value={counts.invited} label="Invited" color="#77a7f5" /><SummaryMetric icon={<Ban size={17} />} value={counts.restricted} label="Restricted" color="#ef5d55" /></SimpleGrid></Box>
    <Box bg="#101010" border="1px solid rgba(255,255,255,.09)" borderRadius="xl" overflow="visible"><Grid templateColumns={{ base: '1fr', lg: 'minmax(280px,1.5fr) repeat(2,minmax(170px,.5fr))' }} gap={3} p={4} borderBottom="1px solid rgba(255,255,255,.08)"><Box position="relative"><Box position="absolute" left={3} top="50%" transform="translateY(-50%)" color="whiteAlpha.500"><Search size={17} /></Box><Input aria-label="Search users" value={search} onChange={(event) => { setSearch(event.target.value); setPage(1) }} placeholder="Search name, email, or handle…" pl={10} h={11} bg="#0c0c0c" borderColor="whiteAlpha.200" color="white" borderRadius="lg" /></Box><select aria-label="Filter by role" value={roleFilter} onChange={(event) => { setRoleFilter(event.target.value as UserRole | 'all'); setPage(1) }} style={selectStyle}><option value="all">All access</option>{roles.map((role) => <option key={role} value={role}>{roleLabel(role)}</option>)}</select><select aria-label="Filter by account state" value={stateFilter} onChange={(event) => { setStateFilter(event.target.value as UserState | 'all'); setPage(1) }} style={selectStyle}><option value="all">All states</option>{Object.entries(stateLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Grid>
      {usersQuery.error && <ErrorStrip message={usersQuery.error.message} />}<Box display={{ base: 'none', lg: 'block' }} overflowX="auto"><Table.Root size="sm" minW="960px" css={{ '& th, & td': { borderColor: 'rgba(255,255,255,.035)' }, '& thead th': { borderColor: 'rgba(255,255,255,.055)' } }}><Table.Header><Table.Row bg="#141414"><Table.ColumnHeader w="46px" />{['User', 'Access', 'Account', 'Last seen', 'Participation', 'Joined'].map((label) => <Table.ColumnHeader key={label} py={3} color="rgba(255,255,255,.5)" fontSize="xs" letterSpacing=".06em" textTransform="uppercase">{label}</Table.ColumnHeader>)}<Table.ColumnHeader w="54px" /></Table.Row></Table.Header><Table.Body>{pageUsers.map((user) => <Table.Row key={user.id} bg={selectedId === user.id ? 'rgba(255,255,255,.055)' : 'transparent'} _hover={{ bg: 'rgba(255,255,255,.04)' }}><Table.Cell pl={4}><Checkbox.Root aria-label={`Select ${user.displayName}`}><Checkbox.HiddenInput /><Checkbox.Control borderColor="whiteAlpha.300" /></Checkbox.Root></Table.Cell><Table.Cell py={3}><UserIdentity user={user} onOpen={(event) => openUser(user, event.currentTarget)} /></Table.Cell><Table.Cell><RoleBadge role={user.role} /></Table.Cell><Table.Cell><StateCell user={user} /></Table.Cell><Table.Cell><Text color="whiteAlpha.700" fontSize="sm">{relativeDate(user.lastActiveAt)}</Text><Text color="whiteAlpha.400" fontSize="xs">{formatDate(user.lastActiveAt, true)}</Text></Table.Cell><Table.Cell><Text color="whiteAlpha.650" fontSize="sm">{user.sessions} sessions</Text><Text color="whiteAlpha.450" fontSize="xs">{user.quests} quests · {user.submissions} submissions</Text></Table.Cell><Table.Cell><Text color="whiteAlpha.600" fontSize="sm">{formatDate(user.createdAt)}</Text></Table.Cell><Table.Cell position="relative"><Button aria-label={`Actions for ${user.displayName}`} onClick={() => setMenuId(menuId === user.id ? null : user.id)} size="sm" minW={9} w={9} h={9} p={0} bg="transparent" color="whiteAlpha.600"><MoreHorizontal size={18} /></Button>{menuId === user.id && <RowMenu user={user} onOpen={() => openUser(user)} onCopy={() => { void navigator.clipboard.writeText(`${window.location.origin}/members/${user.id}`); setFeedback({ tone: 'success', message: 'Public profile link copied.' }); setMenuId(null) }} />}</Table.Cell></Table.Row>)}</Table.Body></Table.Root></Box>
      <VStack display={{ base: 'flex', lg: 'none' }} align="stretch" gap={0}>{pageUsers.map((user) => <MobileUserRow key={user.id} user={user} onOpen={() => openUser(user)} />)}</VStack>{loading && <Box p={10} textAlign="center"><Text color="whiteAlpha.500">Loading live user data…</Text></Box>}{!loading && !pageUsers.length && <Box p={12} textAlign="center"><Text color="white" fontWeight="semibold">No users found</Text><Text color="whiteAlpha.500">Try a different search or filter.</Text></Box>}<Flex px={4} py={3} align="center" justify="space-between" borderTop="1px solid rgba(255,255,255,.08)"><Text color="whiteAlpha.500" fontSize="sm">Showing {filtered.length ? (currentPage - 1) * PAGE_SIZE + 1 : 0}–{Math.min(currentPage * PAGE_SIZE, filtered.length)} of {filtered.length}</Text><HStack gap={1}><PageButton label="Previous page" disabled={currentPage === 1} onClick={() => setPage((value) => Math.max(1, value - 1))}><ChevronLeft size={16} /></PageButton><Text color="whiteAlpha.700" fontSize="sm" px={3}>{currentPage} / {totalPages}</Text><PageButton label="Next page" disabled={currentPage === totalPages} onClick={() => setPage((value) => Math.min(totalPages, value + 1))}><ChevronRight size={16} /></PageButton></HStack></Flex></Box>
  </Box><AnimatePresence>{selectedUser && form && <UserDrawer user={selectedUser} form={form} setForm={setForm} tab={tab} setTab={setTab} authDetails={authDetails} authLoading={authLoading} audit={selectedAudit} saving={saving} onSave={() => save()} onClose={closeDrawer} onStateChange={(status) => { setForm((current) => current ? { ...current, accountStatus: status } : current); void save({ accountStatus: status }) }} />}{inviteOpen && <InviteModal invite={invite} setInvite={setInvite} saving={inviteSaving} onSubmit={createInvite} onClose={() => setInviteOpen(false)} />}{feedback && <Toast tone={feedback.tone} message={feedback.message} onClose={() => setFeedback(null)} />}</AnimatePresence></AdminLayout>
}

function SummaryMetric({ icon, value, label, color }: { icon: ReactNode; value: number; label: string; color: string }) { return <HStack px={4} py={4} gap={3} borderRight="1px solid rgba(255,255,255,.07)" _last={{ borderRight: 0 }}><Box color={color}>{icon}</Box><Box><Text color="white" fontWeight="bold" lineHeight={1}>{value}</Text><Text color="whiteAlpha.500" fontSize="xs" mt={1}>{label}</Text></Box></HStack> }
function Avatar({ user, size = 42 }: { user: ManagedUser; size?: number }) { return <Flex w={`${size}px`} h={`${size}px`} minW={`${size}px`} overflow="hidden" borderRadius="full" bg="whiteAlpha.100" border="1px solid rgba(255,255,255,.08)" align="center" justify="center" color="whiteAlpha.700" fontWeight="bold">{user.avatar ? <Image src={user.avatar} alt="" w="full" h="full" objectFit="cover" /> : user.displayName.charAt(0).toUpperCase()}</Flex> }
function UserIdentity({ user, onOpen }: { user: ManagedUser; onOpen: (event: React.MouseEvent<HTMLButtonElement>) => void }) { return <Button onClick={onOpen} variant="ghost" h="auto" p={0} color="white" textAlign="left"><HStack gap={3}><Avatar user={user} /><Box minW={0}><Text fontWeight="semibold" fontSize="sm" truncate>{user.displayName}</Text><Text color="whiteAlpha.450" fontSize="xs" truncate>@{user.username}</Text></Box></HStack></Button> }
function RoleBadge({ role }: { role: UserRole }) { return <Badge bg={role === 'admin' ? 'rgba(255,107,53,.14)' : 'rgba(255,255,255,.07)'} color={role === 'admin' ? '#ff9b76' : 'rgba(255,255,255,.74)'} border="1px solid rgba(255,255,255,.09)" px={2.5} py={1} borderRadius="full" textTransform="none">{roleLabel(role)}</Badge> }
function StateCell({ user }: { user: ManagedUser }) { const colors: Record<UserState, string> = { active: '#65c466', onboarding: '#e4b93f', invited: '#77a7f5', suspended: '#ef6a62', closed: '#8b8b8b' }; return <Box><HStack gap={2}><Box w={2} h={2} borderRadius="full" bg={colors[user.state]} /><Text color={colors[user.state]} fontSize="sm">{stateLabels[user.state]}</Text></HStack>{user.state === 'active' && <Text pl={4} color="whiteAlpha.400" fontSize="xs">In good standing</Text>}</Box> }
function RowMenu({ user, onOpen, onCopy }: { user: ManagedUser; onOpen: () => void; onCopy: () => void }) { return <Box position="absolute" right={3} top={11} zIndex={12} minW="190px" p={1.5} bg="#191919" border="1px solid rgba(255,255,255,.13)" borderRadius="lg" boxShadow="0 16px 40px rgba(0,0,0,.45)"><MenuButton onClick={onOpen}>Manage user</MenuButton><MenuButton onClick={onCopy}><Copy size={15} /> Copy public profile</MenuButton>{user.accountStatus !== 'active' && <Text px={3} py={2} color="orange.200" fontSize="xs">Account access is restricted</Text>}</Box> }
function MenuButton({ children, onClick }: { children: ReactNode; onClick: () => void }) { return <Button onClick={onClick} w="full" justifyContent="flex-start" gap={2.5} size="sm" bg="transparent" color="whiteAlpha.800" _hover={{ bg: 'whiteAlpha.100' }}>{children}</Button> }
function MobileUserRow({ user, onOpen }: { user: ManagedUser; onOpen: () => void }) { return <Button onClick={onOpen} variant="ghost" h="auto" p={4} borderBottom="1px solid rgba(255,255,255,.035)" borderRadius={0} color="white" textAlign="left"><Flex w="full" justify="space-between" gap={3}><HStack gap={3} minW={0}><Avatar user={user} /><Box minW={0}><Text fontWeight="semibold" truncate>{user.displayName}</Text><Text color="whiteAlpha.450" fontSize="xs" truncate>{user.email}</Text></Box></HStack><VStack align="flex-end" gap={1}><RoleBadge role={user.role} /><Text color="whiteAlpha.500" fontSize="xs">{relativeDate(user.lastActiveAt)}</Text></VStack></Flex></Button> }
function PageButton({ children, label, ...props }: { children: ReactNode; label: string; disabled: boolean; onClick: () => void }) { return <Button aria-label={label} {...props} size="sm" minW={9} w={9} h={9} p={0} bg="transparent" color="whiteAlpha.700">{children}</Button> }

function UserDrawer({ user, form, setForm, tab, setTab, authDetails, authLoading, audit, saving, onSave, onClose, onStateChange }: { user: ManagedUser; form: EditForm; setForm: React.Dispatch<React.SetStateAction<EditForm | null>>; tab: DrawerTab; setTab: (tab: DrawerTab) => void; authDetails: AuthDetails | null; authLoading: boolean; audit: AuditLog[]; saving: boolean; onSave: () => void; onClose: () => void; onStateChange: (status: UserAccountStatus) => void }) {
  const changed = form.displayName !== user.displayName || form.email !== user.email || form.username !== user.username || form.role !== user.role || form.accountStatus !== user.accountStatus; const tabs: Array<{ id: DrawerTab; label: string }> = [{ id: 'overview', label: 'Overview' }, { id: 'access', label: 'Access' }, { id: 'activity', label: 'Activity' }, { id: 'account', label: 'Account' }, { id: 'audit', label: 'Audit' }]
  return <Flex position="fixed" inset={0} zIndex={80} bg="rgba(0,0,0,.58)" justify="flex-end" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose() }}><MotionBox role="dialog" aria-modal="true" aria-label={`Manage ${user.displayName}`} initial={{ x: 60, opacity: 0 }} animate={{ x: 0, opacity: 1 }} exit={{ x: 60, opacity: 0 }} w={{ base: '100%', md: 'min(680px, 52vw)' }} h="100vh" bg="#101010" borderLeft="1px solid rgba(255,255,255,.12)" display="flex" flexDirection="column" boxShadow="-20px 0 60px rgba(0,0,0,.35)"><Box p={{ base: 4, md: 6 }} borderBottom="1px solid rgba(255,255,255,.09)"><Flex justify="space-between" align="flex-start" gap={4}><HStack gap={4} align="flex-start"><Avatar user={user} size={64} /><Box><Heading as="h2" color="white" size="md">{user.displayName}</Heading><Text color="whiteAlpha.500" fontSize="sm">@{user.username}</Text><Text color="whiteAlpha.600" fontSize="sm" mt={1}>{user.email}</Text><HStack mt={3} gap={3}><StateCell user={user} /><RoleBadge role={user.role} /></HStack></Box></HStack><Button aria-label="Close user management" onClick={onClose} minW={10} w={10} h={10} p={0} bg="whiteAlpha.50" color="white"><X size={19} /></Button></Flex></Box><HStack gap={0} px={{ base: 2, md: 5 }} borderBottom="1px solid rgba(255,255,255,.09)" overflowX="auto">{tabs.map((item) => <Button key={item.id} onClick={() => setTab(item.id)} flex="0 0 auto" px={3} py={4} h="auto" borderRadius={0} borderBottom="2px solid" borderColor={tab === item.id ? 'brand.500' : 'transparent'} bg="transparent" color={tab === item.id ? 'white' : 'whiteAlpha.500'}>{item.label}</Button>)}</HStack><Box flex={1} overflowY="auto" p={{ base: 4, md: 6 }}>{tab === 'overview' && <OverviewTab user={user} authDetails={authDetails} authLoading={authLoading} />}{tab === 'access' && <AccessTab role={form.role} onChange={(role) => setForm((current) => current ? { ...current, role } : current)} />}{tab === 'activity' && <ActivityTab user={user} authDetails={authDetails} />}{tab === 'account' && <AccountTab form={form} setForm={setForm} user={user} saving={saving} onStateChange={onStateChange} />}{tab === 'audit' && <AuditTab audit={audit} />}</Box><Flex p={4} borderTop="1px solid rgba(255,255,255,.1)" align="center" justify="space-between" gap={4} bg="#121212"><Text color={changed ? 'orange.200' : 'whiteAlpha.400'} fontSize="sm">{changed ? 'You have unsaved changes' : 'All changes saved'}</Text><HStack><Button onClick={onClose} bg="transparent" color="whiteAlpha.700">Cancel</Button><Button onClick={onSave} disabled={!changed || saving} bg="brand.500" color="white">{saving ? 'Saving…' : 'Save changes'}</Button></HStack></Flex></MotionBox></Flex>
}
function OverviewTab({ user, authDetails, authLoading }: { user: ManagedUser; authDetails: AuthDetails | null; authLoading: boolean }) { return <VStack align="stretch" gap={7}><SectionHeading title="Account overview" description="Identity, access state, and trustworthy activity signals." /><SimpleGrid columns={{ base: 1, sm: 2 }} gap={4}><Info label="Member since" value={formatDate(authDetails?.createdAt || user.createdAt)} /><Info label="Last sign-in" value={authLoading ? 'Loading…' : formatDate(authDetails?.lastSignInAt, true)} /><Info label="Last product activity" value={formatDate(user.lastActiveAt, true)} /><Info label="Email" value={authDetails?.emailVerified ? 'Verified' : 'Not verified'} /></SimpleGrid><SimpleGrid columns={3} gap={3}><MiniStat value={user.sessions} label="Confirmed sessions" /><MiniStat value={user.quests} label="Quests completed" /><MiniStat value={user.submissions} label="Submissions" /></SimpleGrid><Box p={4} bg="rgba(119,167,245,.08)" border="1px solid rgba(119,167,245,.2)" borderRadius="lg"><HStack align="flex-start" gap={3}><Activity size={17} color="#77a7f5" /><Text color="whiteAlpha.700" fontSize="sm">Last activity is server-recorded and no longer falls back to profile edits or the join date.</Text></HStack></Box></VStack> }
function AccessTab({ role, onChange }: { role: UserRole; onChange: (role: UserRole) => void }) { const permissions = ROLE_DEFINITIONS[role].permissions; return <VStack align="stretch" gap={6}><SectionHeading title="Access & role" description="Choose the role that matches this person's responsibilities." /><SimpleGrid columns={{ base: 1, sm: 2 }} gap={3}>{roles.map((item) => { const selected = item === role; return <Button key={item} onClick={() => onChange(item)} h="auto" p={4} display="block" textAlign="left" bg={selected ? 'rgba(255,107,53,.10)' : '#151515'} border="1px solid" borderColor={selected ? 'brand.500' : 'whiteAlpha.100'} color="white"><Flex justify="space-between"><Text fontWeight="semibold">{roleLabel(item)}</Text>{selected && <Check size={17} color="#ff7a49" />}</Flex><Text color="whiteAlpha.500" fontSize="xs" mt={2} whiteSpace="normal">{ROLE_DEFINITIONS[item].description}</Text></Button> })}</SimpleGrid><Box><Text color="white" fontWeight="semibold" mb={3}>Effective permissions</Text><VStack align="stretch" gap={2}>{Object.entries(PERMISSION_LABELS).map(([permission, label]) => { const enabled = permissions.includes(permission as never); return <HStack key={permission} gap={3} color={enabled ? 'whiteAlpha.800' : 'whiteAlpha.350'}><Flex w={5} h={5} align="center" justify="center" borderRadius="full" bg={enabled ? 'green.500/15' : 'whiteAlpha.50'} color={enabled ? 'green.300' : 'whiteAlpha.350'}>{enabled ? <Check size={13} /> : <CircleOff size={13} />}</Flex><Text fontSize="sm">{label}</Text></HStack> })}</VStack></Box><Box p={4} bg="yellow.500/8" border="1px solid" borderColor="yellow.500/20" borderRadius="lg"><Text color="yellow.100" fontSize="sm">Changing elevated access revokes existing refresh tokens. The new role applies with the next authenticated token.</Text></Box></VStack> }
function ActivityTab({ user, authDetails }: { user: ManagedUser; authDetails: AuthDetails | null }) { return <VStack align="stretch" gap={5}><SectionHeading title="Activity" description="Authentication and participation are shown separately." /><InfoRow label="Last sign-in" value={formatDate(authDetails?.lastSignInAt, true)} /><InfoRow label="Last product activity" value={formatDate(user.lastActiveAt, true)} /><InfoRow label="Confirmed sessions" value={String(user.sessions)} /><InfoRow label="Approved quests" value={String(user.quests)} /><InfoRow label="Quest submissions" value={String(user.submissions)} /><Text color="whiteAlpha.450" fontSize="xs">Sessions count confirmed registrations. They are not labelled attendance until a check-in record exists.</Text></VStack> }
function AccountTab({ form, setForm, user, saving, onStateChange }: { form: EditForm; setForm: React.Dispatch<React.SetStateAction<EditForm | null>>; user: ManagedUser; saving: boolean; onStateChange: (status: UserAccountStatus) => void }) { const setField = (key: keyof EditForm, value: string) => setForm((current) => current ? { ...current, [key]: value } : current); return <VStack align="stretch" gap={5}><SectionHeading title="Profile & account" description="Changes synchronize with Authentication and the public profile." /><Field label="Display name"><Input value={form.displayName} onChange={(event) => setField('displayName', event.target.value)} /></Field><Field label="Email"><Input type="email" value={form.email} onChange={(event) => setField('email', event.target.value)} /></Field><Field label="Username"><Input value={form.username} onChange={(event) => setField('username', event.target.value)} /></Field><Button asChild variant="outline" borderColor="whiteAlpha.200" color="white"><a href={`/members/${user.id}`} target="_blank" rel="noreferrer"><ExternalLink size={16} /> Open public profile</a></Button><Box mt={4} pt={5} borderTop="1px solid rgba(255,255,255,.1)"><Text color="red.300" fontWeight="semibold">Danger zone</Text><Text color="whiteAlpha.450" fontSize="sm" mt={1} mb={4}>Restricted accounts cannot sign in and their refresh tokens are revoked.</Text><VStack align="stretch" gap={2}>{form.accountStatus === 'active' ? <Button onClick={() => onStateChange('suspended')} disabled={saving} justifyContent="flex-start" bg="transparent" border="1px solid" borderColor="orange.500/30" color="orange.200"><Ban size={16} /> Suspend user</Button> : <Button onClick={() => onStateChange('active')} disabled={saving} justifyContent="flex-start" bg="transparent" border="1px solid" borderColor="green.500/30" color="green.200"><Check size={16} /> Reactivate user</Button>}<Button onClick={() => { if (window.confirm(`Close ${user.displayName}'s account? This preserves audit history.`)) onStateChange('closed') }} disabled={saving || form.accountStatus === 'closed'} justifyContent="flex-start" bg="transparent" border="1px solid" borderColor="red.500/30" color="red.300"><CircleOff size={16} /> Close account</Button></VStack></Box></VStack> }
function AuditTab({ audit }: { audit: AuditLog[] }) { return <VStack align="stretch" gap={5}><SectionHeading title="Audit log" description="Server-written history for administrative changes." />{!audit.length ? <Text color="whiteAlpha.500">No administrative changes recorded yet.</Text> : audit.map((item) => <Box key={item.id} pb={4} borderBottom="1px solid rgba(255,255,255,.08)"><Text color="white" fontSize="sm" fontWeight="medium">{item.action.replace(/_/g, ' ')}</Text><Text color="whiteAlpha.450" fontSize="xs">{formatDate(item.createdAt, true)} · by {item.actorId.slice(0, 10)}…</Text></Box>)}</VStack> }
function SectionHeading({ title, description }: { title: string; description: string }) { return <Box><Heading as="h3" color="white" size="sm">{title}</Heading><Text color="whiteAlpha.500" fontSize="sm" mt={1}>{description}</Text></Box> }
function Info({ label, value }: { label: string; value: string }) { return <Box><Text color="whiteAlpha.450" fontSize="xs" textTransform="uppercase" letterSpacing=".08em">{label}</Text><Text color="whiteAlpha.850" mt={1}>{value}</Text></Box> }
function MiniStat({ value, label }: { value: number; label: string }) { return <Box p={4} bg="#171717" border="1px solid rgba(255,255,255,.08)" borderRadius="lg" textAlign="center"><Text color="white" fontSize="xl" fontWeight="bold">{value}</Text><Text color="whiteAlpha.450" fontSize="xs">{label}</Text></Box> }
function InfoRow({ label, value }: { label: string; value: string }) { return <Flex justify="space-between" gap={4} pb={3} borderBottom="1px solid rgba(255,255,255,.08)"><Text color="whiteAlpha.600">{label}</Text><Text color="white">{value}</Text></Flex> }
function Field({ label, children }: { label: string; children: ReactNode }) { return <Box><Text color="whiteAlpha.600" fontSize="sm" mb={2}>{label}</Text><Box css={{ '& input': { background: '#0d0d0d', borderColor: 'rgba(255,255,255,.15)', color: 'white', borderRadius: '9px' } }}>{children}</Box></Box> }
function InviteModal({ invite, setInvite, saving, onSubmit, onClose }: { invite: InviteForm; setInvite: React.Dispatch<React.SetStateAction<InviteForm>>; saving: boolean; onSubmit: (event: FormEvent) => void; onClose: () => void }) { return <Flex position="fixed" inset={0} zIndex={90} bg="rgba(0,0,0,.72)" align="center" justify="center" p={4} onMouseDown={(event) => { if (event.target === event.currentTarget) onClose() }}><MotionBox role="dialog" aria-modal="true" aria-label="Invite user" initial={{ opacity: 0, scale: .97 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0, scale: .97 }} w="full" maxW="520px" bg="#121212" border="1px solid rgba(255,255,255,.14)" borderRadius="xl"><Flex p={5} justify="space-between" borderBottom="1px solid rgba(255,255,255,.09)"><Heading size="sm" color="white">Invite user</Heading><Button aria-label="Close invite" onClick={onClose} minW={9} w={9} h={9} p={0} bg="whiteAlpha.50" color="white"><X size={17} /></Button></Flex><Box as="form" onSubmit={onSubmit} p={5}><VStack align="stretch" gap={4}><Box p={3} bg="blue.500/8" border="1px solid" borderColor="blue.500/20" borderRadius="lg"><HStack align="flex-start"><KeyRound size={16} color="#77a7f5" /><Text color="whiteAlpha.700" fontSize="sm">Creates the account and copies a secure password-setup link for you to send.</Text></HStack></Box><InviteInput label="Display name" value={invite.displayName} onChange={(value) => setInvite((current) => ({ ...current, displayName: value }))} /><InviteInput label="Email" type="email" value={invite.email} onChange={(value) => setInvite((current) => ({ ...current, email: value }))} /><InviteInput label="Username (optional)" value={invite.username} onChange={(value) => setInvite((current) => ({ ...current, username: value }))} /><Field label="Starting role"><select value={invite.role} onChange={(event) => setInvite((current) => ({ ...current, role: event.target.value as UserRole }))} style={selectStyle}>{roles.filter((role) => role !== 'admin').map((role) => <option key={role} value={role}>{roleLabel(role)}</option>)}</select></Field><HStack justify="flex-end"><Button type="button" onClick={onClose} bg="transparent" color="whiteAlpha.700">Cancel</Button><Button type="submit" disabled={saving} bg="brand.500" color="white">{saving ? 'Creating…' : 'Create invite link'}</Button></HStack></VStack></Box></MotionBox></Flex> }
function InviteInput({ label, value, onChange, type = 'text' }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <Field label={label}><Input type={type} value={value} onChange={(event) => onChange(event.target.value)} /></Field> }
function Toast({ tone, message, onClose }: { tone: 'success' | 'error' | 'warning'; message: string; onClose: () => void }) { const color = tone === 'success' ? '#65c466' : tone === 'warning' ? '#e4b93f' : '#ef6a62'; return <MotionBox role="status" initial={{ opacity: 0, y: -12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -12 }} position="fixed" zIndex={110} top={5} right={5} maxW="390px" p={4} bg="#191919" border="1px solid" borderColor={color} borderRadius="lg"><HStack><Box color={color}>{tone === 'error' ? <AlertTriangle size={17} /> : <Check size={17} />}</Box><Text color="white" fontSize="sm" flex={1}>{message}</Text><Button aria-label="Dismiss notification" onClick={onClose} minW={8} w={8} h={8} p={0} bg="transparent" color="whiteAlpha.500"><X size={15} /></Button></HStack></MotionBox> }
function ErrorStrip({ message }: { message: string }) { return <HStack p={4} bg="red.500/8" color="red.200"><AlertTriangle size={16} /><Text fontSize="sm">{message}</Text></HStack> }
